### ISSUE TITLE
JigsawDataset 里的getitem，为什么采样2*baug

### ISSUE THREAD

**Issue by Linzsd** [xmed-lab/TripleE-DG#1]
您好，请问JigsawDataset 里的getitem，为什么采样2*baug=8个，而不是baug=4个，就像论文中的设置。

**Comment by Linzsd** [comment]
运行程序时，报错没有图片，但我的数据集里是有这个图片的
pretrain model loaded
missing {'projection_head.0.bias', 'projection_head.0.weight', 'embedding.0.weight', 'embedding.0.bias', 'classifier.weight', 'projection_head.1.weight', 'projection_head.1.running_mean', 'projection_head.1.running_var', 'classifier.bias', 'projection_head.3.bias', 'projection_head.1.bias', 'projection_head.3.weight'}
pretrain model loaded
missing {'projection_head.0.bias', 'projection_head.0.weight', 'embedding.0.weight', 'embedding.0.bias', 'classifier.weight', 'projection_head.1.weight', 'projection_head.1.running_mean', 'projection_head.1.running_var', 'classifier.bias', 'projection_head.3.bias', 'projection_head.1.bias', 'projection_head.3.weight'}
pretrain model loaded
missing {'projection_head.0.bias', 'projection_head.0.weight', 'embedding.0.weight', 'embedding.0.bias', 'classifier.weight', 'projection_head.1.weight', 'projection_head.1.running_mean', 'projection_head.1.running_var', 'classifier.bias', 'projection_head.3.bias', 'projection_head.1.bias', 'projection_head.3.weight'}
=> creating model 'resnet18'
Use ESAug with Fourier
Dataset size: train 7491, val 830
Dataset size: test 1670
SubDataset size: subdata1 2497, subdata2 2497, subdata3 2497
  0%|                                                                                          | 0/624 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Administrator\Lin\TripleE-DG-main\main_dg_threemodels.py", line 521, in <module>
    main_worker()
  File "C:\Users\Administrator\Lin\TripleE-DG-main\main_dg_threemodels.py", line 287, in main_worker
    sub_loss_1 = train(sub_train_loader_1, model_1, criterion, ce_criterion, optimizer_1, args)
  File "C:\Users\Administrator\Lin\TripleE-DG-main\main_dg_threemodels.py", line 368, in train
    for i, ((data, class_l, index_dic), d_idx) in enumerate(tqdm(train_loader)):
  File "F:\anacoda\anaconda\envs\pytorch\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "F:\anacoda\anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "F:\anacoda\anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "F:\anacoda\anaconda\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\anacoda\anaconda\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\anacoda\anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataset.py", line 471, in __getitem__
    return self.dataset[self.indices[idx]]
  File "C:\Users\Administrator\Lin\TripleE-DG-main\datasets\dg_dataset.py", line 94, in __getitem__
    return self.datasets[dataset_idx][sample_idx], dataset_idx
  File "C:\Users\Administrator\Lin\TripleE-DG-main\datasets\dg_dataset.py", line 220, in __getitem__
    image = self.get_image(index)
  File "C:\Users\Administrator\Lin\TripleE-DG-main\datasets\dg_dataset.py", line 200, in get_image
    img = Image.open(framename).convert('RGB')
  File "F:\anacoda\anaconda\envs\pytorch\lib\site-packages\PIL\Image.py", line 2968, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Administrator/Lin/TripleE-DG-main/DATASET/PACS/kfold/sketch/giraffe/n02439033_11894-6.png'
